pengutronix/genimage

- .travis.yml
- Makefile.am
- configure.ac
- genimage.c
- genimage.h
- image-file.c
- image-rauc.c
- image-ubi.c
- test/basic-images.test
- test/cpio.config
- test/cramfs.config
- test/ext2.config
- test/ext3.config
- test/ext4.config
- test/flash-types.config
- test/flash.config
- test/hdimage.config
- test/iso.config
- test/jffs2.config
- test/sharness.sh
- test/squashfs.config
- test/tar.config
- test/ubi.config
- test/ubifs.config
- test/vfat.config
- util.c
Some warning fixes and some very basic tests.
> Cleanup and testing

- genimage.c
Fix partitions from sub-sub dirs.
> Fix partitions

- configure.ac
This is a generic mailing list for open source tools maintained by
Pengutronix.
Note that GitHub remains the preferred location for patch submission and
discussion.
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>
> configure.ac: use oss-tools@pengutronix.de for mails

- .travis.yml
- Makefile.am
- README.rst
- config.c
- genimage.c
- genimage.h
- image-qemu.c
- test/basic-images.test
- test/qemu.config
- test/qemu.info
Resuming pull-request #28 from a clean branch.
> add qemu handler

- test/basic-images.test
> test: set umask to ensure that the test content is always the same

- .travis.yml
> test: install mtd-utils for more test coverage

- README.rst
Fix trivial typo in README.rst
>  Fix README ("has_journral" to "has_journal")

- image-rauc.c
> image-rauc: make sure the manifest option is set

- README.rst
- image-hd.c
- test/hdimage.config
Use the existing 'autoresize' partition option for this.
> hdimge: allow the last partition to fill the rest of the image

- image-rauc.c
RAUC supports PKCS#11 URLs instead of filenames for the --cert and --key
arguments:
https://rauc.readthedocs.io/en/latest/advanced.html#pkcs-11-support
So do not add cert and key as image partitions if the "pkcs11" prefix
is detected.
Signed-off-by: Bastian Krause <bst@pengutronix.de>
> image-rauc: support PKCS#11 URLs for cert/key

- Makefile.am
> Makefile.am: add new files

- configure.ac
> release version 12

- configure.ac
> release version 13

- .github/workflows/tests.yml
> .github: build on ubuntu-16.04 as well

- configure.ac
> release version 14

- Makefile.am
- README.rst
- genimage.c
- genimage.h
- image-hd.c
- list.h
- test/basic-images.test
- test/gpt-overlap1.config
- test/gpt-overlap2.config
- test/gpt-overlap3.config
- util.c
This list of commit in #143 is getting rather long. So lets split out some of cleanups and simpler changes and merge those first.
> image-hd changes spit out from #143

- genimage.h
- image-rauc.c
- util.c
Pass intermediate parameter from config file to rauc command line.
Signed-off-by: Denis Osterland-Heim <Denis.Osterland@diehl.com>
> add rauc intermediate option

- Makefile.am
- image-hd.c
- test/basic-images.test
- test/hdimage6.config
- test/hdimage6.fdisk
> extended partition fix and test cleanup

- test/basic-images.test
> test: fix copy/paste error in the test refactoring

- configure.ac
> release version 15

- configure.ac
> release version 16

- Makefile.am
- test/ext.test
- test/ext2test-percent.2.dump
- test/ext2test.2.dump
- test/ext3test.2.dump
- test/ext4test.2.dump
- test/mke2fs.1.dump
- test/mke2fs.2.dump
- test/mke2fs.3.dump
> tests: ext: use different output files to compare to instead of trying to patch the output

- image-hd.c
Just some cleanup without functional changes.
> image-hd: cleanup
