pengutronix/genimage

image-ext2.c, image-vfat.c
The `size' property is mandatory and cannot be 0 for vfat and ext file
systems.
Print a message that is more helpful than:
genext2fs: too few blocks. Note: options have changed, see --help or the man page.
ext2(test.ext2): failed to generate test.ext2
and
mkdosfs: unable to discover size of images/test.vfat
vfat(test.vfat): failed to generate test.vfat
Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>
=> vfat, ext2: print error message when size is zero

image-hd.c
This lead to an accidental offset, ultimatively leading to not bootable
hd images.
Fixes: 5d3fd814bd23 ("image-hd: fix offset validation")
Signed-off-by: Bastian Stender <bst@pengutronix.de>
=> image-hd: fix offset in case of no offset/partition table

util.c
Print the suffix to get a more precise message when the suffix is
invalid.
For example, it prints the following trace when size is '7.5M':
Invalid size suffix '.5M' in '7.5M'
Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>
=> util: print suffix error

Makefile.am, image-hd.c, test/basic-images.test, test/hdimage.config, test/hdimage.fdisk-2
The hdimage property "primary-partitions" limits the number of primary
partitions recorded into the Master Boot Record.
Limiting the number of primary partitions to 2 into the MBR allows to
create Extended Partition Boot Record scheme images. This kind of images
is composed of one primary and one extended partition.
Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>
=> image-hd: set the position of extended partition

image-hd.c
With no extended partition 'hd->extended_partition' is zero. As a result
'has_extended' is set incorrectly.
The extended partition number is now defined explicitly so we can use it to
define 'has_extended'.
Fixes: c17203afa2d6 ("image-hd: set the position of extended partition")
=> image-hd: fix partition handling

image-file.c, image-ubi.c, util.c
The current behaviour is not very informative:
```
hdimage(hd.img): adding partition 'root' (in MBR) from 'root.ext2' ...
hdimage(hd.img): failed to write image partition 'root'
hdimage(hd.img): failed to generate hd.img
```
Now I have at least a hint why it fails:
```
hdimage(hd.img): adding partition 'root' (in MBR) from 'root.ext2' ...
hdimage(hd.img): write /path/to/hd.img: No space left on device
hdimage(hd.img): failed to write image partition 'root'
hdimage(hd.img): failed to generate hd.img
```
The first commits also fix errno handling in the existing code base.
=> pad_file, insert_data: be more verbose on errors

image-vfat.c, test/basic-images.test, test/vfat.config
Mtools by default refuses to work with filesystems not fitting the legacy
C-H-S adressing, E.G. bigger than 511MB or with "odd" sizes.
mkdosfs writes a BIOS parameter block containing (among others) the number
of sectors per track and heads.  This parameter block is what mtools reads
and validates that total sectors is a multiple of sectors/track times heads.
For small(<512MB) filesystems, mkdosfs uses sectors/track = 32 and heads =
64, allowing filesystems of multiples of 1MB to validate.  For bigger
filesystems it instead uses sectors/track = 63 and heads = 255 to signify
LBA addressing.  63 * 255 * 512 bytes is not a multiple of 1MB, so the
validation in mtools fails for filesystems of multiples of 1MB, E.G:
image test.fat {
vfat {
files = { "test.txt" }
}
size = 512M
}
Errors out …
=> config.c: disable mtools C-H-S adressing check by default

genimage.c
After the mv/mkdir of the mountpoints the timestamps of the mountpoint and all
parent dirs are changed.
This patch adds a find/touch loop to fix the timestamp of all directories.
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
=> genimage: fix timestamp of mountpoint directories

image-ext2.c
By default when using mk2efs the root_owner is "0:0", this adds an option to specify the root_owner option in mk2efs defaulting to "0:0" if the root_owner option is not in the config file.
=> image-ext: add root_owner option

image-ext2.c, test/mke2fs.config
Alle other multi word options use '-' as well.
=> image-ext2: rename option mke2fs_conf -> mke2fs-conf

image-hd.c
Bit 2 of the GPT partition table entry "flags" attribute allows to
mark the partition as bootable, so we add support for setting this
flag, using the same bootable flag used for MBR partition tables.
Setting this flag is useful to properly support the "Generic Distro"
concept from U-Boot [1], which searches for boot scripts in the
bootable partition.
[1] http://git.denx.de/?p=u-boot.git;a=blob;f=doc/README.distro
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
=> image-hd: add support for bootable flags on GPT

.travis.yml, Makefile.am, README.rst, config.c, genimage.c, genimage.h, test/basic-images.test, test/ext2percent.config, test/ext2test-percent.dump, util.c
=> allow percentages for image sizes

util.c
The size of the output file is checked here, not the input file.
=> pad_file: fix copy/paste error in an error message

README.rst, image-hd.c
Disk signature is part of PARTUUID for MBR partitions. PARTUUID can be
used to provide root partition, instead of hardcoding /dev/sd* or
/dev/mmcblk* nodes. The advantage of using PARTUUID is that it doesn't
change across reboots (depending on device drivers probe order).
Up to now 0 value has been used for disk signature if user didn't
provide one. Change behavior to generate unique disk signature in such
case, so we make it less likely to have multiple SD cards with the same
PARTUUIDs connected to a single system, resulting in PARTUUID conflict.
Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
=> hdimage: use random mbr disk signature if not provided

genimage.c
This turned out to be easier than I expected. Bodes well for me hacking on the code in the future!
Closes #67.  Thanks for this extremely useful tool.
=> Prefix mountpoints with mp- to avoid conflict with "root"

README.rst, image-hd.c
This allows the user to specify the location of the GPT table.  This is
useful if a device requires that the bootloader be located in a location
that conflicts with the normal location of the GPT table.
Also, this changes the calculation of the "first usable LBA" to be the
first *listed* partition; this allows the calculation to disregard the
non-listed bootloaders that make this feature useful.  It is up to the
user to ensure that the GPT table is in a location that does not
conflict with any non-listed partition entries.
Comments welcome.
=> hdimage: Implement 'gpt-location' option to move GPT table

image-hd.c, test/basic-images.test
And add some more hd image sanity checks to 'make check'.
=> image-hd: the secondary GPT header should point to the secondary GPT table

test/basic-images.test, util.c
When generating large HD images with little content, it is very useful to be
able to generate a sparse image.
This takes the simple approach by just replacing a write of all zeroes with a
seek forward in the file and then setting the desired file size at the end.
Signed-off-by: Stefan Sørensen <stefan.sorensen@spectralink.com>
=> hdimage: Implement sparse support

README.rst, genimage.c, genimage.h, image-ext2.c, image-jffs2.c, image-ubifs.c, image-vfat.c, util.c
This is useful when creating multiple images with on config and some of
them should be empty. Also, vfat filesystems cannot be empty right now, so
this makes it possible.
=> make it easier to create empty filesystems

image-ubifs.c
Otherwise genimage will crash if lebsize is zero.
Fixes #68.
=> image-ubifs: validate lebsize

util.c
Hi,
On large filesystem, we have the error `Too many open files`.
Here you can find the patch correcting the problem (27f9030).
Thanks,
Herve
=> Error `Too many open files`

Makefile.am
Somehow this file didn't make it into the released tarballs, resulting in a serious lack of documentation.
=> Makefile: add README.rst to release tarball

image-ext2.c
genimage does not pass the config options 'features' to mke2fs when
option 'use-mke2fs' is set to true. If the latter option is not set,
genext2fs is called instead and tune2fs is run on the image afterwards
passing those features.
By not passing that features the behaviour contradicts the documentation
and the user expectations.
Fixes: #81
Signed-off-by: Alexander Dahl <ada@thorsis.com>
=> image-ext: Pass 'features' to mke2fs

util.c
With old kernel headers, AT_NO_AUTOMOUNT flag is not defined.
Fixes #91
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
=> util: define AT_NO_AUTOMOUNT if needed

genimage.c, genimage.h, image-hd.c
This allows users to instruct Windows 10 to ignore certain partitions to
various extent.
I am creating a backup tool based on Linux and I would like to hide the partition containing the Linux system from Windows users so that they don't get confused.
=> image-hd: Add GPT attributes for hiding partitions on Windows

README.rst, image-hd.c
In order to boot a raspberry pi using GPT one must use a Hybrid MBR partition scheme since the firmware looks for the first available MBR fat32 partition.
Example config:
```
image boot.vfat {
vfat {
files = {
"bcm2710-rpi-3-b.dtb",
"bcm2710-rpi-3-b-plus.dtb",
"bcm2837-rpi-3-b.dtb",
"rpi-firmware/bootcode.bin",
"rpi-firmware/cmdline.txt",
"rpi-firmware/config.txt",
"rpi-firmware/fixup.dat",
"rpi-firmware/start.elf",
"rpi-firmware/overlays",
"Image"
}
}
size = 32M
}
image sdcard.img {
hdimage {
gpt = "true"
}
partition boot {
partition-type = 0xC
partition-type-uuid = c12a7328-f81f-11d2-ba4b-00a0c93ec93b
bootable = "true"
image = "boot.vfat"
}
partition rootfs {
partition-uuid = c0932a41-44cf-463b-8152-d43188553ed4
partition-type-uuid = b921b045-1df0-41c3-af44-4c6f280d3fae
image = …
```
=> Add support for Hybrid MBR partitions

image-ext2.c, test/mke2fs.dump
This is necessary for 64 bit timestamps. Those are needed to handle the
year 2038 problem.
This is necessary for smaller filesystems because mke2fs uses the
'usage-type' 'small' by default for filesystems smaller than 512MB.
This includes a 128 inode size.
=> image-ext2: always use inode size 256 with mke2fs

image-flash.c
Add partition size check similar to the one in hdimage_setup.
Ensures that images do not exceed partition size
I've been bitten by this issue today, resulting in half a u-boot SPL written to a SPI nor flash image and an hour of debugging.
=> image-flash: Abort if size of image exceeds partition size

image-flash.c
According to the documentation a flash image is
> the partition contents padded to the partition sizes concatenated together
Currently empty partitions are not padded to size, resulting in overall
size not equal to the sum of all partition sizes if the last partition
is empty.
=> image-flash: Pad empty flash partitions to size

image-flash.c, image-hd.c, util.c
Before this, the interpretation of the 'size' argument depended on the
'infile'. If no 'infile' was given, then 'size' was the final size of the
total image.
If an 'infile' was given, then 'size' was the number of bytes to add to the
images.
This is confusing, so change it to always mean the full size the image is
supposed to be once pad_file() is done.
Fixes: adf18f077010 ("image-flash: Pad empty flash partitions to size")
=> util: pad_file: always use the full image size for the size argument

util.c
Previous to this commit calling `map_file_extents` on an effectively
empty file (either true zero size or an empty sparse file) caused
genimage to segfault.
This is a consequence of FS_IOC_FIEMAP returning 0 mapped extents for
effectively empty files. `map_file_extents` relies on
`number of mapped extent`s > 0 wihtout ever checking it, resulting in
an integer underflow and subsequent segfault due to an out of bounds
memory access.
This commit fixes the issue by checking the number of mapped extents
is not 0 before trying to access the last extent.
Signed-off-by: Tobias Schramm <t.schramm@manjaro.org>
=> util: fix segfault in map_file_extents for effectively zero size files

README.rst
=> README: RAUC key/cert can be PKCS#11 URIs

README.rst, image-rauc.c, test/rauc.config
A keyring can be specified in genimage's config similar to "cert" and "key". The keyring is passed to the "rauc bundle" command which makes sure the signed bundle can be verified against that keyring.
This is especially helpful for use cases that exceed a single key pair with self-signed certificate, such as a PKI or a keyring consisting of multiple certificates.
=> image-rauc: allow optional keyring verification

config.c
this option will print an easily parse-able `genimage` version defined as `PACKAGE_VERSION` in the `config.h` file.
=> introduce `-v/--version` option

genimage.c
The "ret" variable in image_setup is not initialized when an image does
not contain any partitions and the image handler does not provide a
setup function. This can cause image_setup to error out erroneously.
These conditions are fulfilled by the cpio test case, but this bug only
becomes visible when the stack content aligns accordingly.
Initialize ret to 0, as image_setup can be considered successful in this
case.
Signed-off-by: Florian Larysch <fl@n621.de>
=> genimage: initialize return value

util.c
Using genimage (for buildroot) on Ubuntu-20.04.1 on WSL fails
with (see [1] for details):
ERROR: hdimage(sdcard.img): fiemap .../buildroot-2020.08-rc1/images/boot.vfat: 25 Inappropriate ioctl for device
This is because the fiemap ioctl sets errno to ENOTTY instead of the
expected EOPNOTSUPP.
[1] https://bugs.busybox.net/show_bug.cgi?id=13146
Signed-off-by: Peter Seiderer <ps.report@gmx.net>
=> util: add fiemap fallback for errno ENOTTY

README.rst, genimage.c, genimage.h
When using something like
image @IMAGE@ {
....
partition sysdata {
image = "sysdata"
in-partition-table = true
partition-type-uuid = "L"
}
}
image sysdata {
size = 200M
ext4 {}
empty = true
}
to create a partition containing an empty file system, it's
undesirable to leave such an empty file system image in the output
directory (especially when building with Yocto, where it then gets
copied to the shared deploy directory).
So allow specifying an image as temporary, putting it in in tmppath()
rather than imagepath().
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>
=> allow specifying an image as temporary

config.c, image-ext2.c, image-hd.c, image-iso.c, image-rauc.c, image-vfat.c
This fixes the following warnings when compiling with CC=cgcc:
config.c:197:46: warning: Using plain integer as NULL pointer
image-ext2.c:208:9: warning: Using plain integer as NULL pointer
image-ext2.c:212:9: warning: Using plain integer as NULL pointer
image-ext2.c:213:9: warning: Using plain integer as NULL pointer
image-hd.c:663:11: warning: symbol 'hdimage_opts' was not declared. Should it be static?
image-iso.c:52:9: warning: Using plain integer as NULL pointer
image-rauc.c:191:9: warning: Using plain integer as NULL pointer
image-vfat.c:130:9: warning: Using plain integer as NULL pointer
Note, you might want to also use libconfuse with https://github.com/libconfuse/libconfuse/pull/148, otherwise there are just too many warnings resulting from macros defined there.
If you like this …
=> Make sparse clean

README.rst
The `fill` option is required if hd images are to be processed with programs such as `parted` or `guestfish`.
For instance, without it, parted will abort, stating that the partition end lies beyond the end of the device/file.
However, `fill` is not documented in the README.rst, which makes it hard(er) to find that it exists and is related to the issue.
Adding the option to the README.rst will make `fill` easier to spot.
=> Document fill option in README.rst

image-hd.c, test/basic-images.test
The backup partition table at the end of the image for GPT consists of an
odd number of sectors. The size of filesystem images or the explicit size
of a partition is almost always a multiple of 4k. Unless explicitly
configured otherwise, the beginning of all partitions is also multiple of
4k. So when the backup partition table is appended directly after the last
partition then the image size is most likely not a multiple of 4k.
This causes problems with tools such as 'fastboot'.
If the image size is not specified explicitly and GPT is used then increase
the image size if necessary to ensure that it is a multiple of 4k.
=> image-hd: align image size to 4k when using GPT

.github/workflows/tests.yml
Some repos may become unavailable or move, thus one should always run `apt-get update` prior to `apt-get install`.
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>
=> .github: run apt-get update to update package cache

image-ext2.c
Allow to override block-size from config file.
Signed-off-by: Denis Osterland-Heim <Denis.Osterland@diehl.com>
=> image-ext: ensure size is always interpreted as kilobytes

config.c
If the config file does not include a 'config' section, the parsing
produces a warning: "no sub-section title/index for 'config'".
Silence this by checking if the section exists before accessing it.
Fixes #144
=> config: don't try to access non-existent section

image-vfat.c, test/basic-images.test
It enables the 'Batch  mode'. It is optimized for huge recursive copies. This is not
really needed here and fsck.vfat complains about the resulting filesystem.
So drop the option and expand the existing test. Fail if fsck.vfat modifies the
filesystem.
Fixes #142
=> image-vfat: drop '-b' from mcopy

image-android-sparse.c
On a 64 bit system off_t can hold signed, 64 bit integers. Putting large off_t values in a 32 bit int results in overflows. These overflows trigger the "< 0" check and result in errors. This can be observed on large input images.
lseek() returns an off_t, so introduce an off_t to store its return value appropriately.
=> image-android-sparse: use off_t instead of int for lseek return values

util.c
This patch changes systemp() to use the shell defined in the environment
variable SHELL rather then hard coded /bin/sh, so that the called
programs can use shell functions exported in the calling shell. Use
"/bin/sh" as a fall back.
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
=> util: systemp(): use shell defined in SHELL rather than /bin/sh

image-hd.c, image-squashfs.c
When generating a squashfs image as part of an overall image-hd build, the squashfs does not actually get included in the intended partitions. These are an attempt at fixing that. I've tested the patches by seeing that the sd card is now generated as expected, but I don't have time ATM to write proper unit tests for genimage itself.
=> handle squashfs image size

README.rst, config.c, genimage.c, genimage.h, image-hd.c, util.c
A few things I hit when trying to use genimage as part of bootstrapping an eMMC device. The first commit is of course not strictly required, but useful for debugging.
=> Assorted fixups

genimage.h, image-ext2.c, image-flash.c, image-hd.c, image-vfat.c, util.c
So far, each image type has its own initialization code. This creates a helper function for this and starts using it.
=> Add and use helper function to initialize an image

README.rst, genimage.c, genimage.h
Fixes #181
Allows user to override the complexity of rootpath/mountpoint and just simply use existing directory at arbitrary path if needed.
Now i can create ext4 filesystem like this:
```
image root.img {
ext4 {
label = "rootlabel"
}
size = 1024M
srcdir = "./root"
}
```
`genimage --inputpath "." --outputpath "."`
=> Override filesystem source path

Makefile.am, README.rst, config.c, genimage.c, genimage.h, image-fip.c, test/basic-images.test, test/fip.config
```
Platforms where ARM Trusted Firmware is the first stage bootloader are
converging to use FIP as bundle format for further firmware including
trusted OS and non secure bootloader. Teach genimage to call fiptool to
generate FIP images. The config options currently supported by genimage
for fip { } nodes are those needed to boot the STM32MP1. The extraargs
config option can be used to add further options as a stop-gap until
genimage is extended as necessary.
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
```
=> Add Firmware Image Package (FIP) support

genimage.c
A set of image environment variables can be used in `exec-pre` and `exec-post`. This "image environment" is specific to the image being generated. `image_generate()` calls itself recursively to resolve dependencies. Because `setenv_image()` is called before `image_generate()`, the set image environment is wrong as soon as `image_generate()` calls itself.
Fix that by setting the image environment inside `image_generate(`) after the point it might call itself for dependency resolution. This way the image environment is always correct.
=> Fix Image Environment

.github/workflows/tests.yml, configure.ac, util.c
It is not available on BSD so add a configure check for it. We already have fallback code in case fallocate() fails, so reuse that when it is missing.
Fixes: #202
=> fix building without fallocate()

genimage.h, util.c
When using genimage on a 32 bit host and trying to populate a ~8GiB eMMC with a GPT image, we hit
INFO: hdimage(/dev/mmcblk0): determined size of block device /dev/mmcblk0 to be 7820083200 ...
ERROR: hdimage(/dev/mmcblk0): seek /dev/mmcblk0: Invalid argument ERROR: hdimage(/dev/mmcblk0): failed to write backup GPT table
This is because the "image->size - GPT_SECTORS*512" aka 7820066304 passed from hdimage_insert_gpt() becomes -769868288 when shoehorned into a "signed long".
Make the offset parameter "unsigned long long" to match the protoype of insert_image().
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>
=> make insert_data take an "unsigned long long" offset

README.rst, genimage.c, genimage.h, image-hd.c
When bootstrapping, it can be useful to ensure that a partition has completely known contents, especially when the partition just contains raw binary data and not a filesystem.
When generating an image file, this is implicitly done already because the non-written parts of the partition(s) are implicitly zero-filled when the containing image file is extended to its final size.
But when using genimage to directly populate a block device, no such implicit zero-filling is done.
Add a "fill" boolean option, and use that to decide between passing the partition's size or the child image's size to insert_image().
=> image-hd: implement "fill" option for partitions

configure.ac, m4/attributes.m4
* `AC_LINK_IFELSE` without `AC_LANG_SOURCE` is deprecated since somewhen around version 2.68.
* `AC_PROG_CC_STDC` has been deprecated In favor of `AC_PROG_CC` with version 2.70. The necessary options for standard C are now determined and added automatically.
=> autoconf: Update scripts for newer versions of autoconf.

configure.ac
Without the call to `LT_INIT` the resulting binary would not contain a proper `RUNPATH` setting when installed to a prefix not covered by the standard library search path.
=> autoconf: Initialize libtool

.github/workflows/tests.yml
Some builds have been erroring or producing warnings, this PR should fix them.
* remove tests on deprecated ubuntu-18.04 image
* upgrade actions to Node 16
=> GitHub Actions Maintenance

util.c
Fixes #221 
Tested this fix using the example that inspired #221, verified that holes in sparse input files are now correctly populated with 0-bytes in the generated flash image, and that nothing else in the generated image changed.
=> Guarantee 0-holes in sparse files are filled with `0` bytes in flash images

README.rst
Just fix what I came across reading the ```android-sparse``` section.
=> Fix Typo in README.rst

image-android-sparse.c, test/misc.test, test/sparse.config
This is  #225 with tests and another fix.
=> image-android-sparse: Fix #224: truncated image generated

README.rst, image-ubifs.c
Allows passing the '-F' flag to force file-system free space to be fixed up on first mount.
=> ubifs: Add configuration for space-fixup

test/hdimage.test
The test for "gpt-partition-types" needs fdisk and sfdisk to be available. The buildtime tests fails if fdisk is not installed.
=> test: hdimage: depend on fdisk and sfdisk

README.rst
The automatic checks for pull requests on Github include a check that fails if a Signed-off-by: line by the commiter is missing in any commit.
It's supposed to mean the "usual semantic also used in other open-source projects" but so far that is not spelled out anywhere.
So add a section to the README to make this explicit.
=> README: Formalize signing off commits

genimage.h, image-rauc.c, test/misc.test, test/rauc.config
This is useful for barebox images on (at least) i.MX8 to be written to eMMC. There the first 32K of the image must be skipped.
=> image-rauc: allow to specify an offset to skip input bytes

.gitignore
`libtool` is an auto-generated file. Hence, ignore it.
=> .gitignore: ignore libtool

README.rst, image-hd.c
barebox has been [documenting](https://github.com/barebox/barebox/commit/ef25a0ce960d) a dedicated GPT partition type GUID for
barebox environment partitions for a while and has started
making [actual](https://github.com/barebox/barebox/commit/9f868f78bc54
) [use](https://github.com/barebox/barebox/commit/287bd01a6a26) of it at runtime in its v2024.03.0 release.
Add a shorthand to make it easier to use.
=> image-hd: gpt: add type GUID shortcut for barebox-env 

image-ext2.c, test/ext2.config, test/ext2percent.config, test/ext3.config, test/ext4.config
mke2fs is actually maintained and generated more modern filesystems. And it can create filesystems that support timestamps beyond 2038.
=> image-ext2: default to mke2fs

test/test-setup.sh
Otherwise, a missing config file is not detected for tests that are expected to fail.
=> run_genimage_impl: abort for missing config file

image-hd.c
All CHS addresses in the EBR should point to absolute address in the image instead of the relative addresses, currently they are only LBA-to-CHS conversion of the relative offsets. If correct, output of `sfdisk -d` of the genimage-produced disk image piped back to `sfdisk file.img` should produce binary identical (see note below) output. However, it is not true, because the CHS addresses differ. Even though the extended partition uses the 0xf type (LBA addressing) and CHS addressing is limited to 1023 sectors, the generated output should be comparable to other tools for easier debugging.
With this change the calculation of CHS addresses of the next EBRs and logical partitions within the extended partition adds the proper offset, so the addresses are absolute within the image.
Note: At …
=> image-hd: fix CHS addresses in EBR

Makefile.am, README.rst, genimage.c, genimage.h, image-hd.c, test/hdimage-fail10.config, test/hdimage-fail11.config, test/hdimage-fail8.config, test/hdimage-fail9.config, test/hdimage-forced-primary.config, test/hdimage-forced-primary.fdisk, test/hdimage.test
The current limitation of Genimage is that it is not able to create MBR images that have primary partitions that start after a logical partition. This can be useful for images that can be later resized based on the actual device size - for this operation the partition must be at the end of the device, and if it is present in a logical partition, it must be resized first, making it a two-step process.
This commit adds the "forced-primary" flag which can be used to indicate that the partition should be put into the disk's MBR instead of creating another logical partition. Validation ensures that this syntax allows to create such partitions only after an existing logical partition, and that the maximum number of MBR entries woudn't be exceeded by doing so.
Test cases for valid and invalid …
=> image-hd: add forced-primary flag for higher MBR layout flexibility

image-ext2.c
When the volume label is set using tune2fs, the parameter is wrapped in single quotes, so do the same when the label is set using mke2fs.  This allows the label to contain spaces and other special characters (except for single quotes!).
=> image-ext2: use single quotes around label for mke2fs

image-hd.c
Refactor and split `hdimage_setup()` to make it easier to understand.
=> Hdimage cleanup

image-android-sparse.c
It contains a reserved field that remains uninitialized otherwise and is written to the output file.
=> image-android-sparse: initialize chunk_header

.github/workflows/tests.yml, Makefile.am, config.c, genimage.c, genimage.h, image-btrfs.c, test/btrfs.config, test/filesystem.test
Based on #232, I've addressed the open comments there and expanded the test.
Closes #158.
Closes #232.
=> Add Btrfs support

test/hdimage.test, util.c
Using genimage directly on an eMMC on target, I'm seeing that the BLKRRPART ioctl fails with EBUSY, presumably because there's still lots of data in flight, and then subsequent parts of my bootstrap procedure fail because the expected partitions can't be found.
Whenever we've written some data, we really should ensure that all data has hit the disk before proceeding, and close() itself is not synchronous.
Add a fsync_close() helper that does exactly what it says on the tin. Use that wherever we close an fd that has been open for writing and actually written to (i.e., no point in doing that in the reload_partitions() function).
Currently, the return value of these close() calls are ignored, so at least for now continue to do that, but at least we do see an error message in case something …
=> util.c: add fsync_close() helper, use where appropriate

README.rst, image-hd.c
U-Boot documents a GPT partition type GUID for U-Boot environment partitions.
Add a shorthand to make it easier to use.
[1] https://github.com/u-boot/u-boot/blob/v2024.10/doc/README.gpt#L288
=> image-hd: gpt: add type GUID shortcut for u-boot-env

README.rst
Document how partition configuration is translated to GPT Flags for GPT partition tables.
=> README: document GPT partition flags

image-hd.c
Before this, the begining of the first partition was used. This leaves
some unusable space between the partition table and the first partition
and causes some Windows versions to alter the GPT.
So set the first usable lba correctly: Set it to the first lba after the
last non-partition data before the first partition.
This will either be directly behind the GPT entry array or, for example
after a bootloader that is placed between the partition table and the
first partition.
Fixes: #262
=> image-hd: set the first usable lba correctly

.github/workflows/tests.yml, Makefile.am, README.rst, genimage.c, genimage.h, image-hd.c, image-mdraid.c, test/mdraid.config, test/misc.test, util.c
This allows to create level 1 MDRAID with 1 device. Can be empty or prepopulated with data image.
Includes unit test using mdadm to check generated image.
Eg.:
```ini
image mdraid-md.img {
mdraid {
level = 1
}
partition data {
image = "mdraid-ext4.img"
}
}
```
It might sound stupid to create single device raid, but it actualy fits my reallife usecase where i pre-generate such raid when making image and user then can very easily add more devices during runtime when needed later. For example like this:
```sh
mdadm --grow /dev/md23 --raid-disks=2 --force
maddm /dev/md23 --add /dev/sdb1
```
Although it should be simple to pre-generate images for all raid members in genimage. It shouldn't be much harder than generating multiple images with the same RAID UUID and few metadata changes. But i …
=> Initial MDRAID support, F2FS documentation

image-flash.c, image-hd.c
Add the missing space in messages such as:
"offset (...) must be amultiple of ... bytes"
=> Add missing space in error messages

Makefile.am, README.rst, genimage.c, genimage.h, image-android-sparse.c, image-flash.c, image-hd.c, image-mdraid.c, test/ext.test, test/hdimage-sparse.config, test/hdimage.test, test/misc.test, test/sparse-fill.config, test/test-setup.sh, util.c
In some cases, preserving 'holes' can be undesirably. So add some options to fill the holes instead:
- `sparse` for partitions, to make the decision on a per partition basis
- `fill-holes` for android sparse images to convert all holes into fill areas
=> Add options to explicitly fill holes

README.rst, image-mdraid.c
I've noticed this thing in mdadm manpage and figured that it would be better option than 'localhost'.
=> MDRAID: Set default homehost to 'any' and mention that in docs

image-hd.c
Check that the partition type is GPT (or hybrid) in case a partition UUID is specified. Make sure that the program does not silinetyl ignores this setting in the partition configuration.
=> image-hd: add a partition type check for partition-uuid

.github/workflows/tests.yml
ubuntu-20.04 is no longer supported. Replace it with the new LTS.
=> .github: replace ubuntu-20.04 with ubuntu-24.04

Makefile.am, image-fip.c, test/fip-size.config, test/misc.test
Until now, the `image->size` of the generated FIP image was 0, which meant that hdimage_generate() did not check if the image fits into the available space of a partition, which could result in an incomplete FIP image if the image was too large and would be overwritten by contents of later partitions. Determine the size of the generated FIP image with a stat() call, so that hdimage_generate() can error out if it does not fit, e.g. in our test case:
```
INFO: hdimage(test.hdimage): adding primary partition 'part1' (in MBR) from 'test.fip' ...
ERROR: hdimage(test.hdimage): part part1 size (512) too small for test.fip (12992)
```
=> image-fip: check size of generated image

Makefile.am, README.rst, config.c, genimage.c, genimage.h, image-erofs.c, test/erofs.config, test/erofs.dump, test/filesystem.test
Erofs is a read-only file-system supported by the Linux Kernel since version 5.4.
This patchset adds basic support, a test & documentation for the filesystem.
This replaces #247. It has some minor fixes (erofs.config was missing in `Makefile.am`.
And there are some extra commits for some options and to extend the test.
=> image-erofs: introduce basic support for erofs

image-hd.c
The code in this section was refactored in commit 77c0335587b8c1097e3d, so the variable is no longer used in this context.
=> image-hd: remove unused variable partition_table_entries

README.rst, config.c, test/filesystem.test
Most recent distros ship util-linux without the compatibility link "mkcramfs" for mkfs.cramfs
=> Make mkfs.cramfs the default for cramfs

test/misc.test
The output format changed again. This time just whitespace changes (tabs vs. spaces) so just ignore those.
=> test: rauc: handle newer versions
